# Generated by Django 5.0 on 2023-12-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='service',
        ),
    ]
