# Generated by Django 5.0 on 2023-12-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_category_event_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('venue_name', models.CharField(max_length=300)),
                ('event_type', models.CharField(max_length=500)),
                ('date_request', models.IntegerField()),
                ('date_end', models.IntegerField()),
                ('desc', models.CharField(max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
