# Generated by Django 5.0 on 2023-12-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='email',
            new_name='n_email',
        ),
    ]
