# Generated by Django 5.0 on 2023-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_email_rent_n_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_request',
            field=models.DateField(),
        ),
    ]
