# Generated by Django 5.0 on 2023-12-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_customer_cart_user_alter_cart_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
