# Generated by Django 5.0 on 2023-12-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
