# Generated by Django 5.0 on 2023-12-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
    ]
